#!/bin/bash

set -exo pipefail

PROJECT="moz-fx-data-backfill-7"
JOB_NAME="gpu-active-backfill"

## this script assumes it's being run from the ingestion-beam directory
## of the gcp-ingestion repo.

mvn compile exec:java -Dexec.mainClass=com.mozilla.telemetry.Decoder -Dexec.args="\
    --runner=Dataflow \
    --jobName=$JOB_NAME \
    --project=$PROJECT \
    --geoCityDatabase=gs://moz-fx-data-prod-geoip/GeoIP2-City/20210105/GeoIP2-City.mmdb \
    --geoIspDatabase=gs://moz-fx-data-prod-geoip/GeoIP2-ISP/20210104/GeoIP2-ISP.mmdb \
    --geoCityFilter=gs://moz-fx-data-prod-dataflow-templates/cities15000.txt \
    --schemasLocation=gs://moz-fx-data-prod-dataflow/schemas/202101060211_e6f3986a.tar.gz \
    --inputType=bigquery_table \
    --input='$PROJECT:payload_bytes_error.backfill_input' \
    --bqReadMethod=export \
    --outputType=bigquery \
    --bqWriteMethod=file_loads \
    --bqClusteringFields=submission_timestamp \
    --output=${PROJECT}:\${document_namespace}_live.\${document_type}_v\${document_version} \
    --errorOutputType=bigquery \
    --errorOutput=${PROJECT}:payload_bytes_error.telemetry \
    --experiments=shuffle_mode=service \
    --region=us-central1 \
    --usePublicIps=false \
    --gcsUploadBufferSizeBytes=16777216 \
"
