#!/bin/bash

### Copy partitions into place for non-telemetry tables

set -exo pipefail

PROJECT=moz-fx-data-backfill-6
: "${DT:=2021-09-03}"
DTNODASH="${DT//-}"

for dataset in $(bq ls -n 1000 --project_id=moz-fx-data-shared-prod | grep '_live' | grep -v 'telemetry_live' | grep -v 'firefox_installer_live'); do
    for table in $(bq ls -n 1000 --project_id=moz-fx-data-shared-prod --format json $dataset | jq -r '.[] | .tableReference.tableId'); do
        bq cp -f \
             "${PROJECT}:${dataset}.${table}\$${DTNODASH}" \
             "moz-fx-data-shared-prod:${dataset}.${table}\$${DTNODASH}"
    done
done
