#!/bin/bash

set -exo pipefail

PROJECT="moz-fx-data-backfill-5"
JOB_NAME="error-geo-backfill"

## this script assumes it's being run from the ingestion-beam directory
## of the gcp-ingestion repo.

mvn compile exec:java -Dexec.mainClass=com.mozilla.telemetry.Decoder -Dexec.args="\
    --runner=Dataflow \
    --jobName=$JOB_NAME \
    --project=$PROJECT  \
    --geoCityDatabase=gs://moz-fx-data-prod-geoip/GeoIP2-City/20200204/GeoIP2-City.mmdb \
    --geoCityFilter=gs://backfill-test-public1/cities15000.txt \
    --schemasLocation=gs://moz-fx-data-prod-dataflow/schemas/202002070142_ce15977.tar.gz \
    --inputType=bigquery_query \
    --input=\"SELECT *, _TABLE_SUFFIX AS pipeline_family FROM \`moz-fx-data-shared-prod.payload_bytes_error.*\` WHERE DATE(submission_timestamp) <= '2020-02-07'\" \
    --bqReadMethod=export \
    --outputType=bigquery \
    --bqWriteMethod=file_loads \
    --bqClusteringFields=submission_timestamp \
    --output=${PROJECT}:payload_bytes_error.\${pipeline_family} \
    --outputTableRowFormat=raw \
    --errorOutputType=bigquery \
    --errorOutput=${PROJECT}:payload_bytes_error.telemetry \
    --experiments=shuffle_mode=service \
    --region=us-central1 \
    --usePublicIps=false \
    --gcsUploadBufferSizeBytes=16777216 \
"
