#!/bin/bash

set -exo pipefail

PROJECT="moz-fx-data-backfill-4"
JOB_NAME="main-1hour-encoded"

## this script assumes it's being run from the ingestion-beam directory
## of the gcp-ingestion repo.

mvn compile exec:java -Dexec.mainClass=com.mozilla.telemetry.Sink -Dexec.args="\
    --runner=Dataflow \
    --jobName=$JOB_NAME \
    --project=$PROJECT  \
    --schemasLocation=gs://moz-fx-data-prod-dataflow/schemas/202005020153_df78ef8.tar.gz \
    --inputType=bigquery_table \
    --input='moz-fx-data-shared-prod:payload_bytes_decoded.telemetry_telemetry__main_v4' \
    --bqReadMethod=storageapi \
    --bqRowRestriction=\"submission_timestamp BETWEEN '2020-05-04T00:00:00' AND '2020-05-04T01:00:00'\" \
    --outputType=bigquery \
    --bqWriteMethod=file_loads \
    --bqClusteringFields=normalized_channel,sample_id \
    --output=${PROJECT}:\${document_namespace}_stable.\${document_type}_encoded \
    --outputTableRowFormat=payload \
    --errorOutputType=bigquery \
    --errorOutput=${PROJECT}:payload_bytes_error.telemetry \
    --experiments=shuffle_mode=service \
    --region=us-central1 \
    --usePublicIps=false \
    --gcsUploadBufferSizeBytes=16777216 \
"
